"""empty message

Revision ID: 135045c56c28
Revises: 
Create Date: 2019-03-22 18:35:57.686328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135045c56c28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('ingresos', sa.Column('referencia', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'ingresos', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_column('ingresos', 'referencia')
    op.drop_column('ingresos', 'empresa_id')
    # ### end Alembic commands ###
