"""empty message

Revision ID: 1d90ef998007
Revises: b16af6fa4aaf
Create Date: 2019-01-27 14:11:51.870328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d90ef998007'
down_revision = 'b16af6fa4aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacto_beneficiario')
    op.drop_table('pagos_egresos')
    op.drop_table('egresos_detalles')
    op.drop_table('beneficiarios')
    op.drop_table('egresos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egresos',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('beneficiario', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_programada_pago', sa.DATE(), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('referencia', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('empresa', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('beneficiarios',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RFC', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cuenta_banco', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('banco', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], name='beneficiarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('egresos_detalles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('centro_negocios', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('proveedor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('concepto', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('numero_control', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], name='egresos_detalles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pagos_egresos',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('referencia_pago', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('forma_pago', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('conciliado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('referencia_conciliacion', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('empresa', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='pagos_egresos_ibfk_1'),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], name='pagos_egresos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('contacto_beneficiario',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('extension', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('puesto', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='contacto_beneficiario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
