"""empty message

Revision ID: 3baecb870892
Revises: 9ae7a34511bd
Create Date: 2019-02-14 17:47:25.868847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baecb870892'
down_revision = '9ae7a34511bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas', sa.Column('numero_cheque', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas', 'numero_cheque')
    # ### end Alembic commands ###
