"""empty message

Revision ID: 4055ca2a8af5
Revises: 3baecb870892
Create Date: 2019-02-14 18:02:24.389418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4055ca2a8af5'
down_revision = '3baecb870892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('pagos_egresos', sa.Column('fecha_conciliacion', sa.String(length=20), nullable=True))
    op.add_column('pagos_egresos', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('pagos_egresos', 'conciliado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_egresos', sa.Column('conciliado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('pagos_egresos', 'status')
    op.drop_column('pagos_egresos', 'fecha_conciliacion')
    op.drop_column('egresos', 'status')
    # ### end Alembic commands ###
