"""empty message

Revision ID: 52c20d8d3e68
Revises: e7b4bfd6fc24
Create Date: 2019-02-22 18:33:00.989932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c20d8d3e68'
down_revision = 'e7b4bfd6fc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiarios', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'status')
    op.drop_column('beneficiarios', 'status')
    # ### end Alembic commands ###
