"""empty message

Revision ID: 62c9a037851c
Revises: 
Create Date: 2019-03-12 18:41:02.882978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62c9a037851c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='categorias')
    op.drop_table('categorias')
    op.drop_table('ingresos_has_pagos')
    op.drop_table('egresos_has_pagos')
    op.drop_index('id', table_name='ingresos')
    op.drop_table('ingresos')
    op.drop_index('id', table_name='egresos_detalles')
    op.drop_table('egresos_detalles')
    op.drop_index('id', table_name='egresos')
    op.drop_table('egresos')
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_index('id', table_name='pagos_ingresos')
    op.drop_table('pagos_ingresos')
    op.drop_index('id', table_name='contacto_beneficiario')
    op.drop_table('contacto_beneficiario')
    op.drop_index('id', table_name='centros_negocio')
    op.drop_table('centros_negocio')
    op.drop_table('clientes')
    op.drop_index('id', table_name='contacto_cliente')
    op.drop_table('contacto_cliente')
    op.drop_table('beneficiario_has_categorias')
    op.drop_index('id', table_name='conceptos')
    op.drop_table('conceptos')
    op.drop_table('empresas')
    op.drop_table('tipo_ingre')
    op.drop_index('id', table_name='beneficiarios')
    op.drop_table('beneficiarios')
    op.drop_index('id', table_name='ingresos_detalles')
    op.drop_table('ingresos_detalles')
    op.drop_index('id', table_name='pagos_egresos')
    op.drop_table('pagos_egresos')
    op.drop_table('formas_pago')
    op.drop_index('id', table_name='cuentas')
    op.drop_table('cuentas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('banco', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('numero_cheque', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='cuentas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'cuentas', ['id'], unique=True)
    op.create_table('formas_pago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pagos_egresos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('referencia_pago', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('fecha_pago', sa.DATE(), nullable=True),
    sa.Column('fecha_conciliacion', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('referencia_conciliacion', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cuenta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('forma_pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='pagos_egresos_ibfk_3'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], name='pagos_egresos_ibfk_1'),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['formas_pago.id'], name='pagos_egresos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'pagos_egresos', ['id'], unique=True)
    op.create_table('ingresos_detalles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('concepto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('centro_negocios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('numero_control', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ingreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='ingresos_detalles_ibfk_2'),
    sa.ForeignKeyConstraint(['centro_negocios_id'], ['centros_negocio.id'], name='ingresos_detalles_ibfk_4'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='ingresos_detalles_ibfk_1'),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], name='ingresos_detalles_ibfk_3'),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], name='ingresos_detalles_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'ingresos_detalles', ['id'], unique=True)
    op.create_table('beneficiarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RFC', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_banco', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('banco', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('comentarios', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'beneficiarios', ['id'], unique=True)
    op.create_table('tipo_ingre',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('empresas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conceptos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='conceptos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'conceptos', ['id'], unique=True)
    op.create_table('beneficiario_has_categorias',
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='beneficiario_has_categorias_ibfk_1'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='beneficiario_has_categorias_ibfk_2'),
    sa.PrimaryKeyConstraint('beneficiario_id', 'categoria_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contacto_cliente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('extension', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('puesto', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='contacto_cliente_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'contacto_cliente', ['id'], unique=True)
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RFC', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_banco', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comentarios', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('banco', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('centros_negocio',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('arrendadora', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='centros_negocio_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'centros_negocio', ['id'], unique=True)
    op.create_table('contacto_beneficiario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('extension', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('puesto', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='contacto_beneficiario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'contacto_beneficiario', ['id'], unique=True)
    op.create_table('pagos_ingresos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('referencia_pago', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_pago', sa.DATE(), nullable=True),
    sa.Column('fecha_conciliacion', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('referencia_conciliacion', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cuenta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('forma_pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='pagos_ingresos_ibfk_3'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], name='pagos_ingresos_ibfk_1'),
    sa.ForeignKeyConstraint(['forma_pago_id'], ['formas_pago.id'], name='pagos_ingresos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'pagos_ingresos', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('password', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('egresos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_programada_pago', sa.DATE(), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_pagado', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_solicitado', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_por_conciliar', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('referencia', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pagado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('beneficiario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], name='egresos_ibfk_1'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='egresos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'egresos', ['id'], unique=True)
    op.create_table('egresos_detalles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('centro_negocios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('proveedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('concepto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('numero_control', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='egresos_detalles_ibfk_3'),
    sa.ForeignKeyConstraint(['centro_negocios_id'], ['centros_negocio.id'], name='egresos_detalles_ibfk_1'),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], name='egresos_detalles_ibfk_4'),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], name='egresos_detalles_ibfk_5'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['beneficiarios.id'], name='egresos_detalles_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'egresos_detalles', ['id'], unique=True)
    op.create_table('ingresos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_ingreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_programada_pago', sa.DATE(), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_pagado', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_solicitado', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('monto_por_conciliar', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pagado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='ingresos_ibfk_2'),
    sa.ForeignKeyConstraint(['tipo_ingreso_id'], ['tipo_ingre.id'], name='ingresos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'ingresos', ['id'], unique=True)
    op.create_table('egresos_has_pagos',
    sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], name='egresos_has_pagos_ibfk_1'),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos_egresos.id'], name='egresos_has_pagos_ibfk_2'),
    sa.PrimaryKeyConstraint('egreso_id', 'pago_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingresos_has_pagos',
    sa.Column('ingreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], name='ingresos_has_pagos_ibfk_1'),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos_ingresos.id'], name='ingresos_has_pagos_ibfk_2'),
    sa.PrimaryKeyConstraint('ingreso_id', 'pago_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'categorias', ['id'], unique=True)
    # ### end Alembic commands ###
