"""empty message

Revision ID: 66215edbc224
Revises: a4a8ba8fa598
Create Date: 2019-03-25 19:50:04.012565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66215edbc224'
down_revision = 'a4a8ba8fa598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conciliaciones_ibfk_3', 'conciliaciones', type_='foreignkey')
    op.drop_constraint('conciliaciones_ibfk_1', 'conciliaciones', type_='foreignkey')
    op.create_foreign_key(None, 'conciliaciones', 'pagos_ingresos', ['ingreso_id'], ['id'])
    op.create_foreign_key(None, 'conciliaciones', 'pagos_egresos', ['egreso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conciliaciones', type_='foreignkey')
    op.drop_constraint(None, 'conciliaciones', type_='foreignkey')
    op.create_foreign_key('conciliaciones_ibfk_1', 'conciliaciones', 'egresos', ['egreso_id'], ['id'])
    op.create_foreign_key('conciliaciones_ibfk_3', 'conciliaciones', 'ingresos', ['ingreso_id'], ['id'])
    # ### end Alembic commands ###
