"""empty message

Revision ID: 8ad29502aa0c
Revises: 1d90ef998007
Create Date: 2019-01-28 16:35:55.906038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ad29502aa0c'
down_revision = '1d90ef998007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_egresos', sa.Column('comentario', sa.String(length=200), nullable=True))
    op.add_column('pagos_egresos', sa.Column('fecha_pago', sa.Date(), nullable=True))
    op.drop_constraint('pagos_egresos_ibfk_2', 'pagos_egresos', type_='foreignkey')
    op.drop_column('pagos_egresos', 'egreso_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_egresos', sa.Column('egreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('pagos_egresos_ibfk_2', 'pagos_egresos', 'egresos', ['egreso_id'], ['id'])
    op.drop_column('pagos_egresos', 'fecha_pago')
    op.drop_column('pagos_egresos', 'comentario')
    # ### end Alembic commands ###
