"""empty message

Revision ID: 98214854345f
Revises: da9c2ecc35a9
Create Date: 2019-02-16 16:19:48.450682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98214854345f'
down_revision = 'da9c2ecc35a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('monto_por_conciliar', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos', 'monto_por_conciliar')
    # ### end Alembic commands ###
