"""empty message

Revision ID: 9ae7a34511bd
Revises: 
Create Date: 2019-02-12 16:58:19.925858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae7a34511bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas', sa.Column('comentario', sa.String(length=250), nullable=True))
    op.add_column('cuentas', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('cuentas', sa.Column('nombre', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'cuentas', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cuentas', type_='foreignkey')
    op.drop_column('cuentas', 'nombre')
    op.drop_column('cuentas', 'empresa_id')
    op.drop_column('cuentas', 'comentario')
    # ### end Alembic commands ###
