"""empty message

Revision ID: a4a8ba8fa598
Revises: f2339a0c16cb
Create Date: 2019-03-25 16:10:11.126923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4a8ba8fa598'
down_revision = 'f2339a0c16cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conciliaciones', sa.Column('cuenta_id', sa.Integer(), nullable=True))
    op.drop_constraint('conciliaciones_ibfk_2', 'conciliaciones', type_='foreignkey')
    op.create_foreign_key(None, 'conciliaciones', 'cuentas', ['cuenta_id'], ['id'])
    op.drop_column('conciliaciones', 'id_cuenta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conciliaciones', sa.Column('id_cuenta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conciliaciones', type_='foreignkey')
    op.create_foreign_key('conciliaciones_ibfk_2', 'conciliaciones', 'cuentas', ['id_cuenta'], ['id'])
    op.drop_column('conciliaciones', 'cuenta_id')
    # ### end Alembic commands ###
