"""empty message

Revision ID: b16af6fa4aaf
Revises: 
Create Date: 2019-01-27 14:03:04.017900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16af6fa4aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pagos_egresos', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos_egresos', type_='unique')
    # ### end Alembic commands ###
