"""empty message

Revision ID: c5a64e2a023b
Revises: 52c20d8d3e68
Create Date: 2019-02-28 12:35:21.148044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5a64e2a023b'
down_revision = '52c20d8d3e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tipo_ingreso_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_programada_pago', sa.Date(), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('monto_total', sa.Numeric(), nullable=True),
    sa.Column('monto_pagado', sa.Numeric(), nullable=True),
    sa.Column('monto_solicitado', sa.Numeric(), nullable=True),
    sa.Column('monto_por_conciliar', sa.Numeric(), nullable=True),
    sa.Column('comentario', sa.String(length=200), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_ingreso_id'], ['tipo_ingre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ingresos_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('centro_negocios_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(), nullable=True),
    sa.Column('numero_control', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('ingreso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['centro_negocios_id'], ['centros_negocio.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], ),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ingresos_has_pagos',
    sa.Column('ingreso_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos_ingresos.id'], ),
    sa.PrimaryKeyConstraint('ingreso_id', 'pago_id')
    )
    op.drop_table('Ingresos')
    op.add_column('pagos_ingresos', sa.Column('fecha_conciliacion', sa.String(length=20), nullable=True))
    op.add_column('pagos_ingresos', sa.Column('monto_total', sa.Numeric(), nullable=True))
    op.add_column('pagos_ingresos', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('pagos_ingresos', 'monto')
    op.drop_column('pagos_ingresos', 'conciliado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_ingresos', sa.Column('conciliado', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('pagos_ingresos', sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.drop_column('pagos_ingresos', 'status')
    op.drop_column('pagos_ingresos', 'monto_total')
    op.drop_column('pagos_ingresos', 'fecha_conciliacion')
    op.create_table('Ingresos',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_programada', sa.DATE(), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('monto_total', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tipo_ingreso_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('empresa', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pagos_ingresos_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='Ingresos_ibfk_1'),
    sa.ForeignKeyConstraint(['pagos_ingresos_id'], ['pagos_ingresos.id'], name='Ingresos_ibfk_3'),
    sa.ForeignKeyConstraint(['tipo_ingreso_id'], ['tipo_ingre.id'], name='Ingresos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('ingresos_has_pagos')
    op.drop_table('ingresos_detalles')
    op.drop_table('ingresos')
    # ### end Alembic commands ###
