"""empty message

Revision ID: da9c2ecc35a9
Revises: 4055ca2a8af5
Create Date: 2019-02-16 15:53:23.315578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9c2ecc35a9'
down_revision = '4055ca2a8af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('monto_solicitado', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos', 'monto_solicitado')
    # ### end Alembic commands ###
