"""empty message

Revision ID: e7b4bfd6fc24
Revises: 98214854345f
Create Date: 2019-02-18 21:09:16.299478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b4bfd6fc24'
down_revision = '98214854345f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos_has_pagos', sa.Column('monto', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos_has_pagos', 'monto')
    # ### end Alembic commands ###
